### PR TITLE
remove gridcontent type parameterization

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
@timholy I've been trying to incorporate most of the changes from your older PR (I made some other changes in the meantime that I needed to work around, also I really wanted to understand everything that was going on), but now I'm a bit surprised at the output of this snippet:

```julia
using SnoopCompile
using GridLayoutBase

tinf = @snoopi_deep begin
    gl = GridLayout()
    gl2 = GridLayout()
    gl[1, 1] = gl2
    nothing
end
```

It seems that there are large flames that are not red, and I thought I'd specifically addressed them in the precompilation file. Why are these lines still being inferred again, is there a trick to it that I'm not getting?

grafik

Somehow all my "improvements" didn't seem to have any effect on timings. I have a little benchmark package which just compares runs across commits/branches and I compared master to my branch for this code:

```julia
# using GridLayoutBase
@timed using GridLayoutBase

# GridLayout constructor
@timed GridLayout()

# Big GridLayout
@timed let
    gl = GridLayout()
    for i in 1:10, j in 1:10, k in 1:10
        gl[i, j] = GridLayout()
    end
end
```

Here's the output, the optimizations branch is not really faster (here it might look like 10ms for `using`, but this measurement also fluctuates quite a bit so it might not be super reliable to time `using` it seems. I expected a clear difference given all the changes I made).

```
6×11 DataFrame
 Row │ version        repetition  name                    juliaversion  commit     allocations  time      gctime     file                               commit_date          date               ⋯
     │ String         Int64       String                  String        SubStrin…  Int64        Float64   Float64    String                             DateTime             DateTime           ⋯
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ optimizations           1  using GridLayoutBase    1.7.1         a07b954      261358885  1.28611   0.0        /Users/juliuskrumbiegel/.julia/d…  2022-01-23T22:58:33  2022-01-23T23:04:2 ⋯
   2 │ optimizations           1  GridLayout constructor  1.7.1         a07b954       56776749  0.661936  0.0435153  /Users/juliuskrumbiegel/.julia/d…  2022-01-23T22:58:33  2022-01-23T23:04:2
   3 │ optimizations           1  Big GridLayout          1.7.1         a07b954     4690200580  8.39461   0.807336   /Users/juliuskrumbiegel/.julia/d…  2022-01-23T22:58:33  2022-01-23T23:04:2
   4 │ master                  1  using GridLayoutBase    1.7.1         d3700e2      261395013  1.37096   0.0        /Users/juliuskrumbiegel/.julia/d…  2022-01-16T11:32:20  2022-01-23T23:04:2
   5 │ master                  1  GridLayout constructor  1.7.1         d3700e2       56776749  0.64803   0.0442939  /Users/juliuskrumbiegel/.julia/d…  2022-01-16T11:32:20  2022-01-23T23:04:2 ⋯
   6 │ master                  1  Big GridLayout          1.7.1         d3700e2     4690200580  8.44522   0.815214   /Users/juliuskrumbiegel/.julia/d…  2022-01-16T11:32:20  2022-01-23T23:04:2

If you have time, I'd be glad for any enlightening thoughts you might have on this :)
```

**Comment by timholy** [comment]
Thanks for picking this up! To explain the flamegraphs...unless the external (Base) code is inlined into your functions, you can't save the inference results---Julia only saves inference results for module-owned methods.

On https://github.com/JuliaLang/julia/pull/43990, here's what the flamegraph looks like:

image

:smile: On that PR I get

```julia
julia> tinf
InferenceTimingNode: 1.951009/1.951067 on Core.Compiler.Timings.ROOT() with 1 direct children
```

whereas on Julia 1.6 I get
```julia
InferenceTimingNode: 2.413862/2.990975 on Core.Compiler.Timings.ROOT() with 71 direct children
```

**Comment by jkrumbiegel** [comment]
Ok cool, so in your new branch basically no additional inference has to run (everything is precompiled and saved)?

I still don't understand though, why something like `GridLayoutBase.compute_rowcols` can't be saved, that's not a Base method. Or which Base code do you mean? I thought everything with backedges to module-owned functions could be saved, but maybe I misunderstood this.

**Comment by timholy** [comment]
> so in your new branch basically no additional inference has to run (everything is precompiled and saved)?

Yep.

> why something like GridLayoutBase.compute_rowcols can't be saved

It immediately demands some Base methods, and those bars are stacked right on top of `compute_rowcols`. (Avoiding broadcasting might work around this?)

But you're right that the presence of `compute_rowcols` is weird. I've recently discovered that there's a process of stripping the inferred code under some circumstances (I haven't fully investigated which circumstances), from https://github.com/JuliaLang/julia/pull/16907. Check this out:

```julia
julia> using GridLayoutBase, MethodAnalysis

julia> mis = methodinstances(GridLayoutBase.compute_rowcols)
1-element Vector{Core.MethodInstance}:
 MethodInstance for compute_rowcols(::GridLayout, ::GeometryBasics.HyperRectangle{2, Float32})

julia> mi = first(mis)
MethodInstance for compute_rowcols(::GridLayout, ::GeometryBasics.HyperRectangle{2, Float32})

julia> mi.backedges
1-element Vector{Any}:
 MethodInstance for align_to_bbox!(::GridLayout, ::GeometryBasics.HyperRectangle{2, Float32})

julia> ci = mi.cache
Core.CodeInstance(MethodInstance for compute_rowcols(::GridLayout, ::GeometryBasics.HyperRectangle{2, Float32}), #undef, 0x00000000000073d6, 0xffffffffffffffff, Tuple{GridLayoutBase.RowCols{Vector{Float32}}, GridLayoutBase.RowCols{Vector{Float32}}}, #undef, nothing, false, false, Ptr{Nothing} @0x0000000000000000, Ptr{Nothing} @0x0000000000000000)

julia> ci.inferred

julia> ci.invoke
Ptr{Nothing} @0x0000000000000000

julia> begin
           gl = GridLayout()
           gl2 = GridLayout()
           gl[1, 1] = gl2
           nothing
       end

julia> ci.inferred

julia> ci.invoke
Ptr{Nothing} @0x00007fa6e6840d00
```
One of the changes in my PR is to stop deleting the inferred code if you're doing precompilation, see the change in my PR to `codegen.cpp`.

**Comment by timholy** [comment]
There's also `@snoopl` to measure the LLVM time. I haven't used it much myself, it was added by Nathan Daly to SnoopCompile.

**Comment by timholy** [comment]
Thanks for tackling this!

Lower priority, but it still might be worth making `Side` and `GridDir` enums rather than types---less specialization means shorter latencies (at least until native-code caching lands) and shorter build times (probably forever). Do you want me to resurrect that from #21? Admittedly there are much bigger fish to fry in Makie-land, so if you don't feel like this is the right time I'd understand 100%.

**Comment by jkrumbiegel** [comment]
I had tried those changes out and they didn't seem to have much effect in timings. Because those were breaking I reversed them then, figuring it was not worth the effort

**Comment by timholy** [comment]
That's reasonable!

**Pull request merged**
