### PR TITLE
Remove asserts from precompile

### PR DESCRIPTION
**Pull request by timholy**
This shouldn't be merged to `master`; instead, there should be a special branch created (e.g., `release-0.4`). However, since that branch doesn't exist I was unable to submit my pull request against it. So this may take a bit of manual work, sorry.

The motivation here is https://github.com/JuliaLang/julia/pull/41447, CC @KristofferC, @vtjnash. Can we get a 0.4.2 release soon?

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
I don't understand, why not master? Release 0.4.2 on a separate branch and then continue on without these changes on master?

**Comment by timholy** [comment]
Right, these are needed to fix older releases of GridLayoutBase that still get used for package-compatibility reasons. master has already switched to `@warnpcfail`, so it doesn't need this change. (We could just delete `@warnpcfail` now, if you prefer, because Julia 1.7 will issue the warning automatically.)

So the steps are:
- `git checkout v0.4.1`
- `git checkout -b release-0.4`
- `git push origin release-0.4`

Then this PR can be merged into `release-0.4`. Either I can resubmit it or you can do a local `git merge`, let me know what you prefer.

**Comment by timholy** [comment]
One other tip: ideally you release 0.4.2 and then make a new 0.6.x release immediately thereafter. GitHub prints the "latest release" based on calendar date, not version number.

But that's just a secondary concern. Perhaps the more important thing to emphasize is that once Julia 1.7 comes out, anyone stuck for [compat] reasons on an older GridLayoutBase won't be able to build Makie unless you merge this and make this 0.4.2 release.

**Comment by timholy** [comment]
Closed in favor of #24, which is against a new `release-0.4` branch.

**Pull request closed without merging**
